name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Triggers when pushing to the main branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main  # Triggers on PR actions for the main branch

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false  # Change to 'true' if using Git Large File Storage (LFS)

      # Step 2: Build and Deploy to Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_MOSS_0BEBA4800 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"

          ###### Repository/Build Configurations ######
          # Paths related to your app's build process
          app_location: "/"  # Location of your app's source code (set to "/" if it's in the root directory)
          api_location: ""   # Leave empty if you don't have an API
          output_location: "build"  # Folder that contains the built static files (React build default is "build")
          ###### End of Repository/Build Configurations ######

  # This job closes the pull request when the event is pull_request closed
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_MOSS_0BEBA4800 }}
          action: "close"
